version: '3'

services:
  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
  pgweb:
    restart: always 
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/test?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres  